services:
  db:
    container_name: postgres
    image: postgres
    entrypoint:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      volumes:
        -db:/data/postgres
      ports:
        - "5332:5432"
      networks:
        - db
      restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: